WIDTH = 1440
HEIGHT = 720
GRID_SIZE = 6
CELL_COUNT = GRID_SIZE ** 2
MINES_COUNT = (GRID_SIZE ** 2) // 4
IMG_BLANK = "Images/MineDefault.png"
IMG_BOMB = "Images/MineBomb.png"
IMG_FLAG = "Images/MineFlag.png"
IMG_ONE = "Images/Mine1.png"
IMG_TWO = "Images/Mine2.png"
IMG_THREE = "Images/Mine3.png"
IMG_FOUR = "Images/Mine4.png"
IMG_FIVE = "Images/Mine5.png"
IMG_SIX = "Images/Mine6.png"
IMG_SEVEN = "Images/Mine7.png"
IMG_EIGHT = "Images/Mine8.png"
